lima-vm/socket_vmnet

- Makefile
**Before:**
```
$ sudo make uninstall
$ ls -l /var/run | grep socket_vmnet
srwxrwx---  1 root          staff           0 Nov  1 15:13 socket_vmnet
-rw-r--r--  1 root          staff           0 Nov  1 15:13 socket_vmnet.stderr
-rw-r--r--  1 root          staff           0 Nov  1 15:13 socket_vmnet.stdout
```
**After:**
```
$ sudo make uninstall
$ ls -l /var/run | grep socket_vmnet
```
> Remove /var/run files on uninstall

- .github/workflows/test.yml
- Makefile
- README.md
- launchd/io.github.lima-vm.socket_vmnet.bridged.en0.plist
- launchd/io.github.lima-vm.socket_vmnet.plist
The previous label was not consistent with other services.
> launchd: fix Label: `io.github.lima-vm.socket_vmnet.plist` -> `io.github.lima-vm.socket_vmnet`

- main.c
I was seeing some instability with my testing of running multiple lima VMs when using the guest-to-guest networking and was seeing that connections would effectively just stop working at seemingly random points.
I think the current code has a bug with removing of the sockets because if the first matching entry is the one we're removing, then we effectively remove all of them. If it's a later entry, we effectively remove all the remaining ones by setting the next to NULL instead of the the possible next entry.
I'm also curious about the malloc on Line 98, I didn't see a corresponding free for it, so I'm curious if there's a leak here too. If that's the case, I'd be happy to take a crack at it, but first wanted to see about this fix.
Caveat: It's been probably over a decade since I used c …
> Fix the bug with linked list removal.

- main.c
Fix the case of removing the last socket. Previous patch missed this case.
We've fixed the pointers, so just break out of the loop.
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
> Fix segv when removing the last socket entry.

- main.c
While debugging the socket issues and running in debug mode, I noticed that there were spurious errors when you perform things like spin up two VMs and then stop one. Looking at the `read` man page looks like 0 means the file has been closed so if that's the case, just be done with socket.
on_accept(): vmnet_return_t VMNET_INVALID_ARGUMENT
vmnet_write: Undefined error: 0
Signed-off-by: Ville Aikas <vaikas@chainguard.dev>
> Remove write on sockets that return EOF (0 bytes). 

- .github/workflows/test.yml
> CI: temporarily disable macos-13

- cli.c
I believe I have discovered a very peculiar bug related to header names. First, a little background. The default filesystem on macOS Is a case-insensitive, case-preserving filesystem. This means that two files sharing the same case-insensitive name cannot exist in the same directory. For example, a directory cannot contain a filed named Test.txt and test.txt; they are, in fact, the same file. This is evident from the output of the "stat" command:
```
% stat -f %i Test.txt
28557750
% stat -f %i test.txt
28557750
```
HFS and APFS can optionally be configured in a case-sensitive mode. Unlike the default case-insensitive, case-preserving mode, the file "Test.txt" and "test.txt" are uniquely separate inodes. If you have access to a case-sensitive filesystem, give it a try.
Now, I discovered …
> Fix to include correct Availability.h header

- README.md
Now that socket_vmnet is available in MacPorts, include installation instructions using MacPorts along side Homebrew.
> Add MacPorts to installation instructions

- .github/workflows/release.yml
- .github/workflows/test.yml
macos-11 is no longer available
https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/
> CI: remove macos-11; update Lima etc.

- main.c
getgrent(3) says:
Note that programs must explicitly set errno to zero before calling any
of these functions if they need to distinguish between a non-existent
entry and an error.
We didn't so we could log the wrong error based on previous failed call and confuse the user.
> Fix incorrect getgrnam error handling

- main.c
We get this signal when writing to a socket when the other side closed the connection. This is wrong since this is not a fatal error. The right way to handle SIGPIPE is to ignore it and handle EPIPE when writing to socket, which we already do.
Fixes: #48
> Ignore SIGPIPE, handle EPIPE

- launchd/io.github.lima-vm.socket_vmnet.bridged.en0.plist
- launchd/io.github.lima-vm.socket_vmnet.plist
Working with multiple lima clusters in the recent weeks I found that socket_vmnet is not running for unknown reason. The typical flow is trying to start the clusters, and lima hostagent fails with connection refused with /var/run/socket_vmnet. This happens to me one or more times in the same day. Trying to run a stress test creating and destroying the lima clusters 50 times fails after several runs and from the point of the failure, all runs failed.
The issue seems to be that socket_vmnet is stopped by launched because it seems to be idle and it is never started again. Adding the keep alive option eliminated this issue.
With this change the daemon is kept running and it should restart after failures.
> Keep the launchd daemon alive

- README.md
The first "succeeds" without sudo:
% /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
Application at path ( /usr/libexec/bootpd ) added to firewall
But then the next command fails:
% /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
The application is not part of the firewall
Running the first command with sudo works:
% sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
Application at path ( /usr/libexec/bootpd ) added to firewall
% /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
Incoming connection to the application is permitted
It looks like Apple bug, the first command should fail if the application was not added to the firewall.
> Fix "IP address is not assigned" troubleshooting

- launchd/io.github.lima-vm.socket_vmnet.bridged.en0.plist
- launchd/io.github.lima-vm.socket_vmnet.plist
According to launchd.plist(5), if ProcessType is left unspecified, the system will apply light resource limits to the job, throttling its CPU usage and I/O bandwidth. Turns out that these resource limits cause lower and unpredictable performance.
Testing ProcessType Interactive increase iperf3 throughput from 1.32 to 3.59 Gbit/s (2.71 times faster).
Before:
% iperf3-darwin -c 192.168.105.58
Connecting to host 192.168.105.58, port 5201
[  5] local 192.168.105.1 port 50333 connected to 192.168.105.58 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd          RTT
[  5]   0.00-1.00   sec   158 MBytes  1.32 Gbits/sec    0   2.91 MBytes   21ms
[  5]   1.00-2.00   sec   163 MBytes  1.36 Gbits/sec    0   3.05 MBytes   19ms
[  5]   2.00-3.00   sec   152 MBytes  1.28 …
> Run socket_vmnet as interactive process

- main.c
We checked for zero read when reading the packet but not when reading the header, so we tried to read zero bytes from the closed socket (which succeeds), and then tried to write zero length packet to vmnet, which fails with VMNET_INVALID_ARGUMENT:
Example logs (from my logging branch):
ERROR| accept: Interrupted system call
ERROR| vmnet_write: [1003] VMNET_INVALID_ARGUMENT
INFO | Closing a connection (fd 5)
ERROR| writev: Bad file descriptor
ERROR| writev: Bad file descriptor
ERROR| vmnet_write: [1003] VMNET_INVALID_ARGUMENT
INFO | Closing a connection (fd 6)
Now we check for zero read and log a clear message:
Connection closed by peer (fd 5)
> Fix error handling when connection closed by peer

- .github/workflows/test.yml
- test/vmnet.yaml
Inject `no_timer_check` to the kernel cmdline as a workaround to lima-vm/lima issue 84 on GitHub Actions.
Fix #55
> CI: fix `Kernel panic - not syncing: IO-APIC + timer doesn't work!`

- .github/workflows/test.yml
- hack/brew-install-version.sh
Lima doesn't seem to work properly with the latest QEMU on GitHub runners.
See also https://github.com/lima-vm/lima/pull/2640
Converted to draft for now; should re-use the script from https://github.com/lima-vm/lima/pull/2642
> Downgrade to qemu-8.2.1

- .github/workflows/release.yml
This allows verifying that the artifacts were built in the lima-vm CI:
```
gh attestation verify socket_vmnet-<VERSION>-<ARCH>.tar.gz --owner lima-vm
```
See:
- https://github.com/actions/attest-build-provenance
- https://github.blog/changelog/2024-06-25-artifact-attestations-is-generally-available/
> Enable actions/attest-build-provenance

- main.c
This does not fix all the issues mentioned in #43 but prepare the infrastructure. With these changes adding timestamps for all logs is a trivial change.
- Log everything to stderr - this has many advantages: much easier to                                                                    
understand what happened before errors, much easier to understand the 
daemon state, since stderr is line buffered, so events (e.g. start,
stop, connect, disconnect) are logged immediately. Easier to get logs
from users.
- Replace fprintf and printf with logging macros (ERRORF, ERROR, INFO)
- Replace perror with ERRORN, showing the same output an error log.
- Use prefix for all logs ("DEBUG|", "INFO |", "ERROR|") to make the 
meaning of the message clear, and make all log message
aligned nicely.
- …
> Improve logging

- main.c
- Minimize semaphore scope
- Replace malloc(); memset() with calloc()
> Minor cleanups

- Makefile
When we make changes to the system, even as developer, we want to log                                                                                                 
the events.
Example install logs:
... 
default     00:36:57.201190+0200    logger  Installing executables for socket_vmnet
v1.1.7-10-gb0725b3 in //opt/socket_vmnet/bin
default     00:36:57.299663+0200    logger  Installing launchd service for socket_vmnet
v1.1.7-10-gb0725b3 in /Library/LaunchDaemons/io.github.lima-vm.socket_vmnet.plist
... 
default     00:42:06.046128+0200    logger  Uninstalling launchd service for socket_vmnet
default     00:42:06.256458+0200    logger  Uninstalling executables for socket_vmnet
> Log make [un]install.* commands

- test/lima.yaml
- test/perf.sh
% test/perf.sh
Usage test/perf.sh command
Available commands:
create                  create test vms 
delete                  delete test vms 
host-to-vm [TIME]       test host to vm performance
host-to-vm-2 [TIME]     test host to vm performance with 1 extra vm
vm-to-vm [TIME]         test vm to vm performance
This may duplicate code in the github workflow, but performance testing cannot be done in github actions. You need a controlled and idle machine to get repeatable results.
> Add performance test using lima and iperf3

- cli.c
On bug fix and various cleanups to keep the code simpler and more idiomatic.
- Don't print usage on memory error (bug fix)
- Replace malloc(), memset() with calloc()
- More idiomatic way to define options
- Shorten option names
- Don't check for NULL before free
- Don't destroy options before exit
- Don't return after exit
> Various cleanups in cli.c

- main.c
The way we used dispatch queue was not optimal, leading to creation of
too many threads, which can cause unneeded context switching, and lower
performance.
We use now 2 queues:
- vms_queue - concurrent queue use to run accepted connections
threads. For this queue we must use concurrent queue since we want to
process requests from VMs in parallel.
- host_queue - serial queue for processing events from vmnet. This queue
is used for the start and stop callback and for the events callback.
With this change we use consistent number of threads: main thread, 1
vmnet thread, 1 thread per connected vm. 
Testing show no change in performance.
| hardware | os     | test          | before (Gb/s) | after (Gb/s) |
|----------|--------|---------------|---------------|--------------|
| M1 Pro   | 14.7.1 …
> Improve dispatch queue usage

- .github/workflows/release.yml
- .github/workflows/test.yml
- Makefile
The macos-12 CI will be completely removed by Dec 3, 2024. (actions/runner-images#10721)
> CI: remove macos-12; add macos-14-large

- .github/workflows/test.yml
- test/vmnet.yaml
- Start iperf3 service instead of using systemd run since this is the standard way to start the server.
- Use iperf3-darwin since it provides additional info (RTT) - without this the job fails.
- Simplify limactl start command
With these changes the macos-15-large test is successful: https://github.com/lima-vm/socket_vmnet/actions/runs/11980467424/job/33404783754
> ci: Cleanup iperf3 tests

- .github/workflows/test.yml
- test/vmnet.yaml
- Use lima from brew
- Add apt-get update before install
- Use plain mode
> ci: More test cleanups

- Makefile
- cli.c
- main.c
Using `-Wall -Wextra -pedantic` revealed 2 places we used compiler extensions, and one copy and paste error, comparing function pointer to 0. Fix the code an enable all warnings.
This can be an issue for portable code, but we build for single platform and single compiler, so we should be ok.
Don't treat warnings as errors to reduced the chance that the build will fail on older macOS versions or future versions.
> Enable all warnings and pedantic mode

- README.md
Removing redundant `brew tap homebrew/services`.
According to [the docs](https://github.com/Homebrew/homebrew-services?tab=readme-ov-file#install) and my own experience, it works automatically without this command.
> Remove redundant command from README.md

- .github/workflows/test.yml
This reverts #63 commit 670aced765263a659eaf8a1f7ab29c3678580271 (ref https://github.com/lima-vm/socket_vmnet/pull/87#issuecomment-2499008033)
Homebrew doesn't seem to manage to build Lima on macos-15.
> Revert "CI: add macos-15-large"

- README.md
When installing from binary, we cannot use make install.lauchd. Add details section with instructions that can be copied and pasted from the readme.
Fixes #97
> Add instructions for installing launchd service

- cli.c
- main.c
The -p option was ignoring it's argument.
And when an early error would jump over the initialization of the dispatch queues, then the attempt to release the queues would cause a segmentation violation.
See also #99
> Fix crashes and -p option

- cli.c
- Reformat long optins idiomatically
- Unify whitespace
> Improve formatting

- main.c
When not using --pidfile option, pidfile_fd is initialized to -1. However if we are interrupted by signal, when we check the value during cleanup, the value is 0(!) and we try to delete a null pidfile and log this error:
^CINFO | Received signal: Interrupt: 2
ERROR| Failed to remove pidfile: "(null)": Bad address
This does not make sense, but we use sigsetjmp(3) for handling signals and its manual mentions:
The sigsetjmp()/siglongjmp() function pairs save and restore the
signal mask if the argument savemask is non-zero; otherwise, only
the register set and the stack are saved.
It seems that pidfile_fd is restored to the value at the time sigsetjmp() was called, which may be 0 (or any other value on the stack). I think this is an old bug, exposed by logging an error when unlink() fails. …
> Fix pidfile cleanup when receiving signal

- main.c
We used sigsetjmp() and siglogjmp() for signal handling, which is very                                                 
hard to use correctly and too magical. Replace it with the kqueue(),
which can notify events on sockets and signals.
The get signals with kqueue, we need to block them. This has the nice
property that no function in any thread will fail with EINTR when we
receive a signal, which simplifies the code.
We setup signal handling before we open the pidfile, so receiving a
signal after the pidfile was created will always remove the pidfile.
Before this change we has a small window when receiving a signal would
terminate the process without removing the pidfile.
To wait for connection or signal, we wait for kqueue events. If we
receiving a signal we break the loop and exit …
> Handle signals with kqueue

- test/lima.yaml
- test/perf.sh
- Use latest ubuntu image matching lima default image
- Simplify iperf3 command, focusing on more recent hardware
> Update performance tests

- .github/workflows/lima.yaml
- test/vmnet.yaml
Testing with vfkit shows that standard runner is stable for running
small vm, so it should work for lima. Lets try to use standard Intel
runner to avoid unnecessary cost.
> Use standard runner for the lima integration test

- test/lima.yaml
- test/perf.sh
- Use vms with 1 cpu for faster and more consistent results
- Use iperf3.service in server vm
- Remove leftover --length argument
> More performance tests tweaks

- test/README.md
- test/lima.yaml
- test/perf.sh
Improve performance test                                                                                                       
- Create N vms (default 2) to allow testing scaling issues
- Run tests with N vms (default 2)
- Run all tests with same vms, instead of starting an stopping the vms 
for each test
- Add vm-to-host test (iperf3 -c server --reverse)
- Add -v option to set the vm type
- Add -b option to test bridged mode
- Store test results in JSON format
- Add command line options instead of positional arguments
- Rename to vms so they are less likely to clash with real vms 
- Minimize vm memory
- Improve logging
- Add test/README.md documenting perf.sh usage
> Improve performance test

- .github/workflows/build.yaml
- .markdownlint.json
- README.md
- test/README.md
Fixes  #79  
added the linting according to the rules discussed 
in `json` 
```bash
{
"MD013": false,
"MD033": false
}
```
> markdown linting added

- .github/dependabot.yml
have added just for the action and workflows as it doesn't work for C dependencies 
fixes #123
> added a dependabot 

- .clang-format
- .github/workflows/build.yaml
- cli.c
- client/main.c
- log.h
- main.c
fixes #104 
- Add `.clang-format` for format file with some set rule
- And To keep consistent format
- refer some pre built style file ( WebKit , LLVM, Microsoft)
- test locally it work on file by running command `clang-format -i <filename>`
- for automation on CI , falling if code is not formatted
- And documentation in `CONTRIBUTING.md`
> feat: add `.clang-format`

- test/lima.yaml
- test/vmnet.yaml
Since Sep 13 updating the vms fail with:
Ign:1 http://archive.ubuntu.com/ubuntu oracular InRelease
Ign:2 http://security.ubuntu.com/ubuntu oracular-security InRelease
Ign:3 http://archive.ubuntu.com/ubuntu oracular-updates InRelease
Err:4 http://security.ubuntu.com/ubuntu oracular-security Release
404  Not Found [IP: 91.189.91.83 80]
Ign:5 http://archive.ubuntu.com/ubuntu oracular-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu oracular Release
404  Not Found [IP: 91.189.91.83 80]
Err:7 http://archive.ubuntu.com/ubuntu oracular-updates Release
404  Not Found [IP: 91.189.91.83 80]
Err:8 http://archive.ubuntu.com/ubuntu oracular-backports Release
404  Not Found [IP: 91.189.91.83 80]
Reading package lists...
E: The repository 'http://security.ubuntu.com/ubuntu oracular-security …
> Update test vms to Ubuntu 25.04
